Repository AY2122S1-CS2103T-F13-4/tp, pull requests merged in 2021-10, with the labels that each got.

#64 add lesson list and relevant methods
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task

#55 minor updates to UG
  docs/UserGuide.md
Labels: documentation

#74 Change hyperlink name in README.md
  README.md
Labels: priority.Medium

#73 UI improvement
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/TuitiONE.png
  src/main/resources/images/help_icon_01.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Task, priority.Medium

#78 Update UserGuide
  docs/UserGuide.md
Labels: documentation

#92 Add Lessons to UI
  docs/images/Ui.png
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Story, priority.High

#113 Branch add lesson command test
  src/test/java/seedu/address/logic/commands/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/address/testutil/LessonBuilder.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
Labels: type.Task, priority.High

#135 Show Student subscription
  src/main/java/seedu/tuitione/model/student/Student.java
  src/main/java/seedu/tuitione/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/tuitione/model/lesson/LessonTest.java
Labels: type.Story

#136 Fix issue where student card does not show total price
  src/main/java/seedu/tuitione/model/student/Student.java
  src/main/java/seedu/tuitione/ui/StudentCard.java
Labels: type.Task

#137 Implement edit student feature
  src/main/java/seedu/tuitione/logic/commands/EditCommand.java
  src/main/java/seedu/tuitione/logic/parser/EditCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/ParserUtil.java
  src/main/java/seedu/tuitione/model/student/Student.java
  src/test/java/seedu/tuitione/testutil/StudentUtil.java
Labels: type.Task

#149 Update user stories, use cases, and add format for implementations in DG
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: documentation

#156 Branch dg unenroll implementation
  docs/DeveloperGuide.md
  docs/diagrams/UnenrollActivityDiagram.puml
  docs/diagrams/UnenrollSequenceDiagram.puml
  docs/diagrams/UnenrollState0.puml
  docs/diagrams/UnenrollState1.puml
  docs/images/UnenrollActivityDiagram.png
  docs/images/UnenrollSequenceDiagram.png
  docs/images/UnenrollState0.png
  docs/images/UnenrollState1.png
Labels: documentation, priority.High

#158 Branch fix clear command bug
  src/main/java/seedu/tuitione/logic/commands/ClearCommand.java
Labels: priority.Medium, severity.VeryLow

#160 DG Mass Update
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeveloperGuideImage/ArchitectureDiagram.png
  docs/images/DeveloperGuideImage/ArchitectureSequenceDiagram.png
  docs/images/DeveloperGuideImage/BetterModelClassDiagram.png
  docs/images/DeveloperGuideImage/CommitActivityDiagram.png
  docs/images/DeveloperGuideImage/ComponentManagers.png
  docs/images/DeveloperGuideImage/DeleteLessonActivityDiagram.png
  docs/images/DeveloperGuideImage/DeleteLessonSequenceDiagram.png
  docs/images/DeveloperGuideImage/DeleteLessonState0.png
  docs/images/DeveloperGuideImage/DeleteLessonState1.png
  docs/images/DeveloperGuideImage/DeleteSequenceDiagram.png
  docs/images/DeveloperGuideImage/EnrollLessonActivityDiagram.png
  docs/images/DeveloperGuideImage/EnrollLessonSequenceDiagram.png
  docs/images/DeveloperGuideImage/EnrollLessonState0.png
  docs/images/DeveloperGuideImage/EnrollLessonState1.png
  docs/images/DeveloperGuideImage/FilterActivityDiagram.png
  docs/images/DeveloperGuideImage/FilterSequenceDiagram.png
  docs/images/DeveloperGuideImage/FilterState0.png
  docs/images/DeveloperGuideImage/FilterState1.png
  docs/images/DeveloperGuideImage/LogicClassDiagram.png
  docs/images/DeveloperGuideImage/LogicStorageDIP.png
  docs/images/DeveloperGuideImage/ModelClassDiagram.png
  docs/images/DeveloperGuideImage/ParserClasses.png
  docs/images/DeveloperGuideImage/SeEduLogo.png
  docs/images/DeveloperGuideImage/StorageClassDiagram.png
  docs/images/DeveloperGuideImage/UiClassDiagram.png
  docs/images/DeveloperGuideImage/UndoRedoState0.png
  docs/images/DeveloperGuideImage/UndoRedoState1.png
  docs/images/DeveloperGuideImage/UndoRedoState2.png
  docs/images/DeveloperGuideImage/UndoRedoState3.png
  docs/images/DeveloperGuideImage/UndoRedoState4.png
  docs/images/DeveloperGuideImage/UndoRedoState5.png
  docs/images/DeveloperGuideImage/UndoSequenceDiagram.png
  docs/images/DeveloperGuideImage/UnenrollActivityDiagram.png
  docs/images/DeveloperGuideImage/UnenrollSequenceDiagram.png
  docs/images/DeveloperGuideImage/UnenrollState0.png
  docs/images/DeveloperGuideImage/UnenrollState1.png
  docs/images/DeveloperGuideImage/github-icon.png
  docs/images/DeveloperGuideImage/helpMessage.png
  docs/images/DeveloperGuideImage/johndoe.png
  docs/images/DeveloperGuideImage/request_access.png
  docs/images/UiClassDiagram.png
  docs/images/UserGuideImage/findAlexDavidResult.png
  docs/tutorials/TracingCode.md
Labels: documentation

#162 Branch dg mass update
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/eezj35.png
  docs/images/github-icon.png
  docs/images/mgrl2201.png
  docs/images/michael-lee-sk.png
  docs/images/muhammad-khair.png
  docs/images/timothyoung97.png
  docs/index.md
Labels: documentation

#173 Update UG to have more 'you' language
  docs/UserGuide.md
Labels: documentation
