Repository AY2122S1-CS2103T-F13-4/tp, pull requests merged in 2021-11, with the labels that each got.

#278 Resolve several similar PE-D issues
  docs/UserGuide.md
  src/main/java/seedu/tuitione/MainApp.java
  src/main/java/seedu/tuitione/commons/core/Messages.java
  src/main/java/seedu/tuitione/commons/util/StringUtil.java
  src/main/java/seedu/tuitione/logic/commands/AddCommand.java
  src/main/java/seedu/tuitione/logic/commands/CommandResult.java
  src/main/java/seedu/tuitione/logic/commands/EnrollCommand.java
  src/main/java/seedu/tuitione/logic/commands/ExitCommand.java
  src/main/java/seedu/tuitione/logic/parser/ParserUtil.java
  src/main/java/seedu/tuitione/model/lesson/Lesson.java
  src/main/java/seedu/tuitione/model/lesson/LessonCode.java
  src/main/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedGrade.java
  src/main/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedGradeAndSubject.java
  src/main/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedLessonCode.java
  src/main/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedSubject.java
  src/main/java/seedu/tuitione/model/lesson/LessonTime.java
  src/main/java/seedu/tuitione/model/lesson/Price.java
  src/main/java/seedu/tuitione/model/lesson/Subject.java
  src/main/java/seedu/tuitione/model/remark/Remark.java
  src/main/java/seedu/tuitione/model/student/Address.java
  src/main/java/seedu/tuitione/model/student/Email.java
  src/main/java/seedu/tuitione/model/student/Grade.java
  src/main/java/seedu/tuitione/model/student/Name.java
  src/main/java/seedu/tuitione/model/student/NameContainsKeywordsPredicate.java
  src/main/java/seedu/tuitione/model/student/ParentContact.java
  src/main/java/seedu/tuitione/model/student/Student.java
  src/main/java/seedu/tuitione/model/student/StudentIsOfSpecifiedGrade.java
  src/main/java/seedu/tuitione/model/student/StudentIsOfSpecifiedLessonCode.java
  src/main/java/seedu/tuitione/storage/JsonSerializableTuitione.java
  src/test/java/seedu/tuitione/logic/commands/EnrollCommandTest.java
  src/test/java/seedu/tuitione/model/lesson/LessonCodeTest.java
  src/test/java/seedu/tuitione/model/lesson/LessonTest.java
  src/test/java/seedu/tuitione/model/student/StudentTest.java
  src/test/java/seedu/tuitione/storage/JsonSerializableTuitioneTest.java
Labels: type.Task

#281 Fix GUI menu colour scheme and border radius
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#282 Update index validity checks and small UI changes
  src/main/java/seedu/tuitione/commons/util/StringUtil.java
  src/main/java/seedu/tuitione/logic/parser/CliSyntax.java
  src/main/java/seedu/tuitione/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/EditCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/ParserUtil.java
  src/main/java/seedu/tuitione/logic/parser/RosterCommandParser.java
  src/main/java/seedu/tuitione/model/ModelManager.java
  src/main/java/seedu/tuitione/model/student/Address.java
  src/main/resources/fonts/open-sans/Montserrat-Bold.ttf
  src/main/resources/fonts/open-sans/Montserrat-SemiBold.ttf
  src/main/resources/images/book.png
  src/main/resources/images/clock_shrinked.png
  src/main/resources/images/house_shrinked.png
  src/main/resources/images/lesson_shrinked.png
  src/main/resources/images/phone_shrinked.png
  src/main/resources/images/size_shrinked.png
  src/main/resources/images/student_shrinked.png
  src/main/resources/images/teach.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LessonListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/tuitione/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/EnrollCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/RosterCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/UnenrollCommandParserTest.java
Labels: type.Task

#286 Resize help window and implement scroll pane for command summary table
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#290 Updates to UG to solve PED issues
  docs/UserGuide.md
Labels: documentation

#285 Update UG
  docs/UserGuide.md
Labels: documentation

#292 Branch-v1.4-MassFix-Tim
  docs/UserGuide.md
Labels: documentation, type.Enhancement

#293 Update UG to solve PE-D issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#288 Update Documentation
  docs/UserGuide.md
  docs/team/muhammad-khair.md
Labels: documentation

#295 Branch fix ug Q&A
  docs/UserGuide.md
Labels: documentation

#291 Updates to PPP
  docs/team/michael-lee-sk.md
  src/main/resources/view/StatusBarFooter.fxml
Labels: documentation

#296 Update individual PPP (Tim)
  docs/team/timothyoung97.md
Labels: documentation

#287 Mass Refactoring of Messages
  src/main/java/seedu/tuitione/commons/core/Messages.java
  src/main/java/seedu/tuitione/commons/util/StringUtil.java
  src/main/java/seedu/tuitione/logic/commands/AddCommand.java
  src/main/java/seedu/tuitione/logic/commands/AddLessonCommand.java
  src/main/java/seedu/tuitione/logic/commands/ClearCommand.java
  src/main/java/seedu/tuitione/logic/commands/CommandResult.java
  src/main/java/seedu/tuitione/logic/commands/DeleteCommand.java
  src/main/java/seedu/tuitione/logic/commands/DeleteLessonCommand.java
  src/main/java/seedu/tuitione/logic/commands/EditCommand.java
  src/main/java/seedu/tuitione/logic/commands/EnrollCommand.java
  src/main/java/seedu/tuitione/logic/commands/ExitCommand.java
  src/main/java/seedu/tuitione/logic/commands/FilterCommand.java
  src/main/java/seedu/tuitione/logic/commands/FindCommand.java
  src/main/java/seedu/tuitione/logic/commands/HelpCommand.java
  src/main/java/seedu/tuitione/logic/commands/ListCommand.java
  src/main/java/seedu/tuitione/logic/commands/RosterCommand.java
  src/main/java/seedu/tuitione/logic/commands/UnenrollCommand.java
  src/main/java/seedu/tuitione/logic/parser/AddCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/DeleteLessonCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/EditCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/EnrollCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/FilterCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/ParserUtil.java
  src/main/java/seedu/tuitione/logic/parser/RosterCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/UnenrollCommandParser.java
  src/main/java/seedu/tuitione/model/lesson/Lesson.java
  src/main/java/seedu/tuitione/model/remark/Remark.java
  src/main/java/seedu/tuitione/model/student/Student.java
  src/main/java/seedu/tuitione/storage/JsonSerializableTuitione.java
  src/main/java/seedu/tuitione/ui/MainWindow.java
  src/test/java/seedu/tuitione/logic/commands/EnrollCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/FilterCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/FindCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/UnenrollCommandTest.java
  src/test/java/seedu/tuitione/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/EnrollCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/ParserUtilTest.java
  src/test/java/seedu/tuitione/logic/parser/RosterCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/UnenrollCommandParserTest.java
  src/test/java/seedu/tuitione/model/lesson/LessonTest.java
  src/test/java/seedu/tuitione/storage/JsonSerializableTuitioneTest.java
Labels: type.Task

#299 Update UG
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/images/help_commands.png
Labels: documentation

#300 Update ppp and improve filter code standard
  docs/UserGuide.md
  docs/team/eezj35.md
  docs/team/muhammad-khair.md
  docs/team/timothyoung97.md
  src/main/java/seedu/tuitione/logic/commands/FilterCommand.java
Labels: documentation, type.Task

#301 Update PPP
  docs/team/mgrl2201.md
Labels: documentation

#302 Updated manual testing instructions for filter and edit + changes to remarks parsing and some exception messages
  docs/DeveloperGuide.md
  docs/team/eezj35.md
  src/main/java/seedu/tuitione/logic/commands/EditCommand.java
  src/main/java/seedu/tuitione/logic/parser/AddLessonCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/EditCommandParser.java
  src/main/java/seedu/tuitione/logic/parser/ParserUtil.java
  src/main/java/seedu/tuitione/model/remark/Remark.java
  src/test/java/seedu/tuitione/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/AddLessonCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/TuitioneParserTest.java
  src/test/java/seedu/tuitione/model/remark/RemarkTest.java
  src/test/java/seedu/tuitione/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/tuitione/testutil/StudentUtil.java
Labels: documentation, type.Task

#303 Update DG diagrams and add Storage instructions
  docs/DeveloperGuide.md
  docs/diagrams/AddLessonActivityDiagram.puml
  docs/diagrams/AddLessonSequenceDiagram0.puml
  docs/diagrams/AddLessonSequenceDiagram1.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteLessonActivityDiagram.puml
  docs/diagrams/DeleteLessonSequenceDiagram0.puml
  docs/diagrams/DeleteLessonSequenceDiagram1.puml
  docs/diagrams/DeleteSequenceDiagram0.puml
  docs/diagrams/DeleteSequenceDiagram1.puml
  docs/diagrams/EnrollLessonSequenceDiagram.puml
  docs/diagrams/EnrollLessonSequenceDiagram0.puml
  docs/diagrams/EnrollLessonSequenceDiagram1.puml
  docs/diagrams/EnrollLessonState1.puml
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram0.puml
  docs/diagrams/FilterSequenceDiagram1.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/UnenrollActivityDiagram.puml
  docs/diagrams/UnenrollSequenceDiagram.puml
  docs/diagrams/UnenrollSequenceDiagram0.puml
  docs/diagrams/UnenrollSequenceDiagram1.puml
  docs/images/DeveloperGuideImage/AddLessonSequenceDiagram.png
  docs/images/DeveloperGuideImage/AddLessonSequenceDiagram0.png
  docs/images/DeveloperGuideImage/AddLessonSequenceDiagram1.png
  docs/images/DeveloperGuideImage/BetterModelClassDiagram.png
  docs/images/DeveloperGuideImage/DeleteLessonActivityDiagram.png
  docs/images/DeveloperGuideImage/DeleteLessonSequenceDiagram.png
  docs/images/DeveloperGuideImage/DeleteLessonSequenceDiagram0.png
  docs/images/DeveloperGuideImage/DeleteLessonSequenceDiagram1.png
  docs/images/DeveloperGuideImage/DeleteSequenceDiagram.png
  docs/images/DeveloperGuideImage/DeleteSequenceDiagram0.png
  docs/images/DeveloperGuideImage/DeleteSequenceDiagram1.png
  docs/images/DeveloperGuideImage/EnrollLessonSequenceDiagram.png
  docs/images/DeveloperGuideImage/EnrollLessonSequenceDiagram0.png
  docs/images/DeveloperGuideImage/EnrollLessonSequenceDiagram1.png
  docs/images/DeveloperGuideImage/EnrollLessonState1.png
  docs/images/DeveloperGuideImage/FilterActivityDiagram.png
  docs/images/DeveloperGuideImage/FilterSequenceDiagram.png
  docs/images/DeveloperGuideImage/FilterSequenceDiagram0.png
  docs/images/DeveloperGuideImage/FilterSequenceDiagram1.png
  docs/images/DeveloperGuideImage/ModelClassDiagram.png
  docs/images/DeveloperGuideImage/ParserClasses.png
  docs/images/DeveloperGuideImage/StorageClassDiagram.png
  docs/images/DeveloperGuideImage/UiClassDiagram.png
  docs/images/DeveloperGuideImage/UndoSequenceDiagram.png
  docs/images/DeveloperGuideImage/UnenrollActivityDiagram.png
  docs/images/DeveloperGuideImage/UnenrollSequenceDiagram.png
  docs/images/DeveloperGuideImage/UnenrollSequenceDiagram0.png
  docs/images/DeveloperGuideImage/UnenrollSequenceDiagram1.png
  docs/images/DeveloperGuideImage/exit_ui.png
  docs/img.png
  src/main/java/seedu/tuitione/MainApp.java
Labels: documentation

#305 Updates to manual testing in DG
  docs/DeveloperGuide.md
  src/main/java/seedu/tuitione/model/util/SampleDataUtil.java
  src/test/java/seedu/tuitione/model/util/SampleDataUtilTest.java
Labels: documentation

#306 Add manual test cases for add, help, list and unenroll
  docs/DeveloperGuide.md
  docs/images/DeveloperGuideImage/help_ui.png
Labels: documentation

#307 Update DG (During Meeting 7/11/2021)
  docs/diagrams/AddLessonActivityDiagram.puml
  docs/diagrams/AddLessonState0.puml
  docs/diagrams/AddLessonState1.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DeleteLessonState0.puml
  docs/diagrams/DeleteLessonState1.puml
  docs/diagrams/EnrollLessonState0.puml
  docs/diagrams/EnrollLessonState1.puml
  docs/diagrams/FilterState0.puml
  docs/diagrams/FilterState1.puml
  docs/diagrams/RosterSequenceDiagram1.puml
  docs/diagrams/RosterState0.puml
  docs/diagrams/RosterState1.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UnenrollState0.puml
  docs/diagrams/UnenrollState1.puml
  docs/images/DeveloperGuideImage/AddLessonActivityDiagram.png
  docs/images/DeveloperGuideImage/AddLessonState0-Initial_state.png
  docs/images/DeveloperGuideImage/AddLessonState1-Final_state.png
  docs/images/DeveloperGuideImage/CommitActivityDiagram.png
  docs/images/DeveloperGuideImage/DeleteLessonState0.png
  docs/images/DeveloperGuideImage/DeleteLessonState1.png
  docs/images/DeveloperGuideImage/EnrollLessonState0.png
  docs/images/DeveloperGuideImage/EnrollLessonState1.png
  docs/images/DeveloperGuideImage/FilterState0.png
  docs/images/DeveloperGuideImage/FilterState1.png
  docs/images/DeveloperGuideImage/RosterActivityDiagram.png
  docs/images/DeveloperGuideImage/RosterSequenceDiagram1.png
  docs/images/DeveloperGuideImage/RosterState0.png
  docs/images/DeveloperGuideImage/RosterState1.png
  docs/images/DeveloperGuideImage/StorageClassDiagram.png
  docs/images/DeveloperGuideImage/UnenrollState0.png
  docs/images/DeveloperGuideImage/UnenrollState1.png
  docs/images/DeveloperGuideImage/help_ui.png
  docs/team/mgrl2201.md
Labels: documentation

#308 Update Send Button
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.Medium, severity.Low

#310 Improve coding standards and additional tests for predicate classes
  src/test/java/seedu/tuitione/logic/commands/DeleteLessonCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/EditCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/EnrollCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/FilterCommandTest.java
  src/test/java/seedu/tuitione/logic/commands/UnenrollCommandTest.java
  src/test/java/seedu/tuitione/logic/parser/DeleteLessonCommandParserTest.java
  src/test/java/seedu/tuitione/logic/parser/ParserUtilTest.java
  src/test/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedGradeAndSubjectTest.java
  src/test/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedGradeTest.java
  src/test/java/seedu/tuitione/model/lesson/LessonIsOfSpecifiedSubjectTest.java
  src/test/java/seedu/tuitione/model/student/StudentIsOfSpecifiedGradeTest.java
Labels: type.Task
